### ISSUE TITLE
Block creation of ProB Notebook until AuthorizationPolicy comes up

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/gatekeeper-policies#15]
This will be the first ticket (of two) for the [RStudio Hardening](https://github.com/StatCan/kubeflow-containers/issues/199) . [This ConstraintTemplate](https://github.com/StatCan/gatekeeper-policies/blob/master/service-mesh/traffic-policy/template.yaml) can be used as a reference.

@wg102 I can help with setting up the kind environment and adding Gatekeeper.

Descendant issue of https://github.com/StatCan/kubeflow-containers/issues/199 

@ca-scribner  I cannot add a project or labels to this issue

**Comment by ca-scribner** [comment]
I think @brendangadd will have to add the project etc to this.  Or add regular daaas people as contributors
