### ISSUE TITLE
Separate AAW from Plaftorm containers in ContainerAllowedImages

### ISSUE THREAD

**Issue by justbert** [StatCan/gatekeeper-policies#7]
There's a blurring of the images being whitelisted via the ContainerAllowedImages/container-allowed-images.

I think it would be beneficial to start separating these two lists since they are from two vastly different platforms.

Is it possible to have multiple ContainerAllowedImages to work together in sequence?

**Comment by justbert** [comment]
So it looks like it isn't possible to have more than one ContainerAllowedImages working at this time.

**Comment by blairdrummond** [comment]
Would there be a way to do this using two ACRs and only letting "system" pods get access to the imagePullSecret?

**Comment by justbert** [comment]
> 
> 
> Would there be a way to do this using two ACRs and only letting "system" pods get access to the imagePullSecret?

I'm not super sure what you're suggesting. 

This policy knows nothing about registries, its sole purpose is to allow or deny images based on a prefix. It is used extensively in the internal environments to ensure image proxying and the solution should not be in relation to AAW specifically.

The goal of this ticket is to start enforcing strong architectural separations between the Cloud Native Platform and the AAW Platform which will lead to easier management and development of both platforms.

**Comment by blairdrummond** [comment]
Oh what I was thinking was more like:

> User namespaces only pull from `coviduser.acr.io/`, and only has that imagePullSecret. Their namespaces cannot pull any other images.

I wasn't thinking so much about the gatekeeper policies, but rather thinking bypassing the limitation of only having one containerAllowedImages.

**Comment by justbert** [comment]
There would be nothing stopping users from adding another imagePullSecret unless you disable their access to secrets.

**Comment by brendangadd** [comment]
See also:
* StatCan/daaas#443
* StatCan/daaas#444

**Comment by sylus** [comment]
Talked with @zachomedia and we can finally close this one out since this repo should only be templates repo with constraint examples.
